### ISSUE TITLE
Testing external links

### ISSUE THREAD

**Issue by warrenv** [poetapp/frost-web#134]
On the home and dashboard pages, there are links for documentation that point to docs.frost.po.et/,
ie, offsite links.

What's the best way to test these types of links?
  - A functional test that clicks on the links to ensure the external site is reachable.
      - Con: CI environments may not have full internet access.
  - A unit test for the component checking that the link is present on the page and has the correct href path.

**Comment by ericelliott** [comment]
There are two different kinds of pages: content pages and application pages.

If the application is actively generating links, it needs unit tests to ensure that the URLs it generates are the expected values.

For content pages (app is not actively generating values), we can let a bot spider those URLs and report unreachable, 404, or 301 errors. The same bot can be reused generically using hypertext to identify and follow links.

In neither case should we read the contents of the destination page and check that it's the correct content, because that's outside the domain of the project under test.

**Comment by warrenv** [comment]
Opened an issue to track this for all projects: https://github.com/poetapp/random/issues/107

**Comment by WesleyCharlesBlake** [comment]
We could build something in Grafana monitor these URLs for 4xx etc and create and alert accordingly. Ie it's something that NOC will be monitoring regardless. But you want the crawler to be triggered as part of the integration tests then we could build something akin to scrapy
